// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKQhQk1uzuDJSAFRlf045grdMK7zaJWls',
    appId: '1:491030896232:web:efbf97d50cbd4c2918a5dd',
    messagingSenderId: '491030896232',
    projectId: 'gym-guide-3abac',
    authDomain: 'gym-guide-3abac.firebaseapp.com',
    storageBucket: 'gym-guide-3abac.firebasestorage.app',
    measurementId: 'G-6CKF2WYJ0M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0HS8KSbqRiAj4Be2U-bDkIlIbjvwuZc4',
    appId: '1:491030896232:android:73f68af56352066e18a5dd',
    messagingSenderId: '491030896232',
    projectId: 'gym-guide-3abac',
    storageBucket: 'gym-guide-3abac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg9ObYSJn3SGKT4A8oAsK0-BrwTbGHK_g',
    appId: '1:491030896232:ios:ffbb1af16c3c5e1918a5dd',
    messagingSenderId: '491030896232',
    projectId: 'gym-guide-3abac',
    storageBucket: 'gym-guide-3abac.firebasestorage.app',
    iosBundleId: 'com.example.gymGuide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCg9ObYSJn3SGKT4A8oAsK0-BrwTbGHK_g',
    appId: '1:491030896232:ios:ffbb1af16c3c5e1918a5dd',
    messagingSenderId: '491030896232',
    projectId: 'gym-guide-3abac',
    storageBucket: 'gym-guide-3abac.firebasestorage.app',
    iosBundleId: 'com.example.gymGuide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKQhQk1uzuDJSAFRlf045grdMK7zaJWls',
    appId: '1:491030896232:web:528cf2d4d25de1c018a5dd',
    messagingSenderId: '491030896232',
    projectId: 'gym-guide-3abac',
    authDomain: 'gym-guide-3abac.firebaseapp.com',
    storageBucket: 'gym-guide-3abac.firebasestorage.app',
    measurementId: 'G-EDX5Y7VB45',
  );
}
